///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace EpointAutomationHelper.Tests
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TestsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("fefe4d66-76e4-4899-b068-5f599272fb79")]
    public partial class TestsRepository : RepoGenBaseFolder
    {
        static TestsRepository instance = new TestsRepository();

        /// <summary>
        /// Gets the singleton class instance representing the TestsRepository element repository.
        /// </summary>
        [RepositoryFolder("fefe4d66-76e4-4899-b068-5f599272fb79")]
        public static TestsRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TestsRepository() 
            : base("TestsRepository", "/", null, 0, false, "fefe4d66-76e4-4899-b068-5f599272fb79", ".\\RepositoryImages\\TestsRepositoryfefe4d66.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("fefe4d66-76e4-4899-b068-5f599272fb79")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class TestsRepositoryFolders
    {
    }
#pragma warning restore 0436
}
