name: CI

on:
  push:
    branches:
      - master

env: # 设置环境变量
  TZ: Asia/Shanghai # 时区（设置时区可使页面中的`最近更新时间`使用时区时间）

jobs:
  build: # 自定义名称
    runs-on: ubuntu-latest # 运行在虚拟机环境ubuntu-latest

    steps:
      - name: Checkout # 步骤1
        uses: actions/checkout@v1 # 使用的动作。格式：userName/repoName。作用：检出仓库，获取源码。 官方actions库：https://github.com/actions
      - name: Setup .NET # 步骤2
        uses: actions/setup-dotnet@v1 # 作用：安装dotnet
        with:
          dotnet-version: 5.0.x # 版本
      - name: Build # 步骤3
        run: dotnet tool install -g Wyam.Tool && wyam new -r Docs && wyam -r Docs
      - name: Deploy # 步骤4 
        uses: JamesIves/github-pages-deploy-action@releases/v2 # 作用：将项目构建和部署到github。 https://github.com/JamesIves/github-pages-deploy-action
        env: # 设置环境变量
          BASE_BRANCH: master # 要部署的文件夹所在的分支
          BRANCH: gh-pages # 部署到的分支
          FOLDER: output # 要部署的文件夹
          BUILD_SCRIPT: cd output echo 'astgeo.github.io/EpointAutomationHelper/' > CNAME && cd - # 部署前要执行的命令（记得cd进入某个目录后，后面要cd -退回开始的目录）
